In [11]:
import numpy as np
import itertools
import math

In [5]:
# 行列による中間層の実装

# 2入力(x0, x1)、2出力(y0, y1)の層には、重み付きユニットが2つある。
# 重み付きユニットの重みは、ユニットごとに定義される。
# 活性化関数もユニットごとに定義できるが、一般的には、同じ層のユニットに対して、
# 同じ活性化関数を定義する。

# y0を求める重み付きユニットの重みを w00, w01, b0 とすると、重み付き入力値の和は
# x0 * w00 + x1 * w01 + b0

# y1を求める重み付きユニットの重みを w10, w11, b1 とすると、重み付き入力値の和は
# x0 * w01 + x1 * w11 + b1

# これら2つの式は、
# x0 * w00 + x1 * w01 + 1 * b0 = [x0 x1 1] * [w00 w01 b0]
# x0 * w10 + x1 * w11 + 1 * b1 = [x0 x1 1] * [w10 w11 b1]
# と変形できるので、
# W = [[w00 w01 -b0] [w10 w11 -b1]], x = [[x0 x1 1] という行列を定めると、
# W と x の行列積としてまとめることができる。

w00, w01, b0 = 0.5, 0.5, -0.7
w10, w11, b1 = 0.4, 0.4, -0.2
W2_2 = np.asarray([[w00, w01, b0], [w10, w11, b1]])

x0, x1 = 0, 1
x2 = np.asarray([x0, x1, 1])

print(W2_2.shape)
print(x2.shape)

print(W2_2 @ x2)

(2, 3)
(3,)
[-0.2  0.2]


In [10]:
# 上の式は入力と出力がどちらも2の場合を示していたが、
# 入力と出力の数が2以外の場合でも、行列積の式は同じとなる。

# 重みの行列
# 3行5列 => 出力は3つ、入力は4つ
W4_3 = np.random.randint(2, size=(3, 5))
print(W4_3)

# 入力の行列
x4 = np.asarray([1, 0, 0, 1, 1])

# 各ユニットの重み付け入力値の和
print(W4_3 @ x4)

# 1行9列 => 出力は1つ、入力は8つ
W8_1 = np.random.randint(2, size=(1, 9))
print(W8_1)

# 入力の行列
x8 = np.asarray([1, 0, 0, 1, 1, 0, 1, 0, 1])

# 各ユニットの重み付け入力値の和
print(W8_1 @ x8)

[[0 0 1 1 1]
 [1 0 1 1 1]
 [1 1 0 1 0]]
[2 3 2]
[[1 0 1 0 0 1 1 1 1]]
[3]


In [18]:
# 中間層の実装の一般化

# 中間層のクラス
class NeuralNetworkLayer:
    # コンストラクタ
    # n_input: 入力信号の数
    # n_output: 出力信号の数
    # activator: 活性化関数
    def __init__(self, n_input, n_output, activator):
        self.W = np.random.randint(2, size=(n_output, n_input + 1))
        self.activator = activator
    
    # 入力信号から出力信号を求める。
    # x: 入力信号
    def propagate(self, x):
        # 重み付き入力値の和を求める。
        s = self.W @ x
        # 活性化関数の値を求める。
        return self.activator(s)

# 活性化関数の定義
step = np.frompyfunc(lambda x: 1 if x > 0 else 0, 1, 1)
sigmoid = np.frompyfunc(lambda x: 1 / (1 + math.exp(-x)), 1, 1)

In [19]:
# 中間層の使用例1: 4入力3出力、ステップ関数による活性化
layer0 = NeuralNetworkLayer(4, 3, step)
print(layer0.W)
print(layer0.propagate(np.asarray([1, 0, 0, 1, 1])))

# 中間層の使用例2: 8入力1出力、シグモイド関数による活性化
layer1 = NeuralNetworkLayer(8, 1, sigmoid)
print(layer1.W)
print(layer1.propagate(np.asarray([1, 0, 1, 1, 1, 0, 0, 0, 1])))

[[0 1 0 1 0]
 [1 1 1 1 0]
 [0 0 0 1 1]]
[1 1 1]
[[0 1 0 0 1 1 0 1 1]]
[0.8807970779778823]
